default:
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

.tests-common:
  only:
    changes:
      - Dockerfile
      - app.js
      - test.js

stages:          # List of stages for jobs, and their order of execution
#  - build
  - test


#build-job:       # This job runs in the build stage, which runs first.
#  stage: build
#  script:
#    - echo "Compiling the code..."
#    - echo "Compile complete."

mocha-test-job:
  extends: .tests-common   
  stage: test    
  script:
    - npm test


lint-test-job:   
  extends: .tests-common
  stage: test    
  script:
    - npm run lint
