.tests-common:
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  only:
    changes:
      - Dockerfile
      - app.js
      - test.js

stages:   
  - test
  - build

build-job:      
  stage: build
  tags:
    - build
  script:
    - docker info

mocha-test-job:
  extends: .tests-common   
  stage: test    
  script:
    - npm test


lint-test-job:   
  extends: .tests-common
  stage: test    
  script:
    - npm run lint
