.tests-common:
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  only:
    changes:
      - Dockerfile
      - app.js
      - test.js

.docker-common:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:   
  - test
  - build
  - deploy

build-job:      
  stage: build
  tags:
    - build
  script:
    - docker info
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest

deploy-job:
  stage: deploy
  tags:
    - docker
  script:
    - docker run $CI_REGISTRY/group/project/image:latest

mocha-test-job:
  extends: .tests-common   
  stage: test    
  script:
    - npm test


lint-test-job:   
  extends: .tests-common
  stage: test    
  script:
    - npm run lint
